# Generated by Django 4.2.1 on 2025-08-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='profile/anonim.png', null=True, upload_to='profile/%Y/%m/%d/', verbose_name='Аватарка'),
        ),
    ]
