# Generated by Django 4.2.1 on 2025-08-17 21:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, verbose_name='Информация о себе'),
        ),
    ]
