# Generated by Django 4.2.1 on 2025-10-03 14:55

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_date_birth_alter_user_description_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
