# Generated by Django 4.2.1 on 2025-08-06 19:32

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='cat',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', related_query_name='where_posts', to='women.category', verbose_name='Категории'),
        ),
    ]
