# Generated by Django 4.2.1 on 2025-08-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_alter_comment_options_comment_level_comment_lft_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
