# Generated by Django 4.2.1 on 2025-08-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='photo',
            field=models.ImageField(blank=True, default='photos/placeholder300.jpg', null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
