# Generated by Django 4.2.1 on 2025-08-17 20:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_alter_women_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст статьи'),
        ),
    ]
