# Generated by Django 4.2.1 on 2025-08-17 21:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_alter_women_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Комментарий'),
        ),
    ]
