# Generated by Django 4.2.1 on 2025-09-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0011_rating'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['is_published'], name='is_published_idx'),
        ),
    ]
