# Generated by Django 4.2.1 on 2025-09-22 11:34

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import women.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('women', '0012_women_is_published_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='husband',
            options={'verbose_name': 'Man', 'verbose_name_plural': 'Men'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('-time_create',), 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='women',
            options={'get_latest_by': ['time_create'], 'ordering': ['-time_create'], 'verbose_name': 'Famous women', 'verbose_name_plural': 'Famous women'},
        ),
        migrations.AddField(
            model_name='category',
            name='name_be',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_be',
            field=models.SlugField(max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_ru',
            field=models.SlugField(max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='comment',
            name='body_be',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='tagpost',
            name='slug_be',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='tagpost',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='tagpost',
            name='slug_ru',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='tagpost',
            name='tag_be',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='tagpost',
            name='tag_en',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='tagpost',
            name='tag_ru',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='women',
            name='content_be',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='women',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='women',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='women',
            name='slug_be',
            field=models.SlugField(max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='women',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='women',
            name='slug_ru',
            field=models.SlugField(max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='women',
            name='title_be',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(5, message='The title is too short'), women.validators.RussianValidator()], verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='women',
            name='title_en',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(5, message='The title is too short'), women.validators.RussianValidator()], verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='women',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(5, message='The title is too short'), women.validators.RussianValidator()], verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='women.category', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of create'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='women.comment', verbose_name='Parent comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='women.women', verbose_name='Title of the post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of update'),
        ),
        migrations.AlterField(
            model_name='husband',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='husband',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='women.women', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of create'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='tagpost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tagpost',
            name='tag',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='image',
            field=models.FileField(upload_to='uploads_model', verbose_name='Upload an image'),
        ),
        migrations.AlterField(
            model_name='women',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='women',
            name='cat',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', related_query_name='where_posts', to='women.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='women',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='women',
            name='husband',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='woman', to='women.husband', verbose_name='Husband'),
        ),
        migrations.AlterField(
            model_name='women',
            name='is_published',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='women',
            name='photo',
            field=models.ImageField(blank=True, default='photos/placeholder300.jpg', null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='women',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', related_query_name='tags', to='women.tagpost', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='women',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time create'),
        ),
        migrations.AlterField(
            model_name='women',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Time update'),
        ),
        migrations.AlterField(
            model_name='women',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='The title is too short'), women.validators.RussianValidator()], verbose_name='Title'),
        ),
    ]
