# Generated by Django 4.2.1 on 2025-09-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0013_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagpost',
            name='slug_be',
        ),
        migrations.RemoveField(
            model_name='tagpost',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='tagpost',
            name='slug_ru',
        ),
    ]
