# Generated by Django 4.2.1 on 2025-09-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0014_remove_tagpost_slug_be_remove_tagpost_slug_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug_be',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_ru',
        ),
    ]
