# Generated by Django 4.2.1 on 2025-09-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0015_remove_category_slug_be_remove_category_slug_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='slug_be',
        ),
        migrations.RemoveField(
            model_name='women',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='women',
            name='slug_ru',
        ),
    ]
