# Generated by Django 4.2.1 on 2025-09-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0016_remove_women_slug_be_remove_women_slug_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='title_be',
        ),
        migrations.RemoveField(
            model_name='women',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='women',
            name='title_ru',
        ),
    ]
