# Generated by Django 4.2.1 on 2025-10-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0017_remove_women_title_be_remove_women_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
